import { z } from "zod";

import type { ProviderUrlConfig } from "./index.js";

// ============================================================================
// LIVEOHANA.AI QUERY PARAMETER SCHEMA
// ============================================================================
//
// Verified against the live site on 2026-05-09 via browser automation.
// LiveOhana is a mid-term rental / sublease marketplace (Bubble.io SPA).
// Focused on 1-12 month stays — the gap between Airbnb and 12-month leases.
// Strong in NYC, SF, Boston, LA. Raised ~$4M.
//
// URL format: https://liveohana.ai/search?params
//
// Params are consumed client-side by the Bubble.io SPA.
// Multi-value params use comma-separated strings.
// Values with spaces get URL-encoded; Bubble may double-encode (%2520 in URL).
//
// Full filter panel verified via browser:
//   Price (min/max), Available Bedrooms (Any/1-6), Type of Place (Any/Entire
//   home/Private room), Amenities (In-unit laundry/Building laundry/Gym/Doorman),
//   Roommate gender (Female/Male/Non-binary), Roommates (max: Any/1-5),
//   Pets (All/Pets allowed/Pets prohibited).
//   Note: Roommate gender + Roommates only visible when Type of Place = Private room.
//
// URL params confirmed by applying filters and observing URL changes:
//   location, movein, moveout, min_price, max_price, bedrooms,
//   property_types, type_of_places, amenities, pet_policy,
//   furnished_status, roommate, max_roommates.
//
// ⚠️  COLD URL HYDRATION (params that actually filter on page load):
//   ✅ Works: location, movein, moveout, min_price, max_price, property_types
//   ❌ Ignored: bedrooms, type_of_places, amenities, pet_policy,
//              furnished_status, roommate, max_roommates
//   Bubble.io reads some params on hydration but not all. The ignored params
//   only take effect when set via the internal Bubble state (UI interactions).
//   We still include all params in the schema because:
//     1. They appear in URLs generated by the site itself (shareable links)
//     2. Bubble may fix hydration for these params in the future
//     3. The serializer produces valid URLs matching what the UI generates
// ============================================================================

// ---------------------------------------------------------------------------
// Property type values (from URL observation)
// ---------------------------------------------------------------------------

export const OHANA_PROPERTY_TYPES = {
  APARTMENT: "Apartment",
  HOUSE: "House",
} as const;

// ---------------------------------------------------------------------------
// Type of place values (accommodation type — from filter panel)
// ---------------------------------------------------------------------------

export const OHANA_PLACE_TYPES = {
  /** Entire home/apartment — full unit to yourself */
  ENTIRE_HOME: "Entire home",
  /** Private room — your own room in a shared space */
  PRIVATE_ROOM: "Private room",
} as const;

// ---------------------------------------------------------------------------
// Amenities (from filter panel)
// ---------------------------------------------------------------------------

export const OHANA_AMENITIES = {
  IN_UNIT_LAUNDRY: "in-unit laundry",
  BUILDING_LAUNDRY: "building laundry",
  GYM: "gym",
  DOORMAN: "doorman",
} as const;

// ---------------------------------------------------------------------------
// Pet policy values (from filter panel + URL)
// ---------------------------------------------------------------------------

export const OHANA_PET_POLICY = {
  ALLOWED: "pets allowed",
  PROHIBITED: "pets prohibited",
} as const;

// ---------------------------------------------------------------------------
// Furnished status values (from URL observation)
// ---------------------------------------------------------------------------

export const OHANA_FURNISHED_STATUS = {
  /** Move-in ready — furnished and ready to go */
  MOVE_IN_READY: "Move-in ready",
  /** Furnished */
  FURNISHED: "Furnished",
  /** Unfurnished */
  UNFURNISHED: "Unfurnished",
} as const;

// ---------------------------------------------------------------------------
// Roommate gender values (from filter panel + URL)
// ---------------------------------------------------------------------------

export const OHANA_ROOMMATE_GENDER = {
  FEMALE: "Female",
  MALE: "Male",
  NON_BINARY: "Non-binary",
} as const;

// ---------------------------------------------------------------------------
// Zod schema
// ---------------------------------------------------------------------------

export const liveohanaParamsSchema = z.object({
  // --- Location ---
  location: z
    .string()
    .optional()
    .describe(
      "Free-text location string, typically a city or address with state/zip. " +
        "Examples: 'New York', 'San Francisco, CA, USA', " +
        "'San Francisco International Airport (SFO), San Francisco, CA 94128, USA'. " +
        "Supports any geocodable string. Gets URL-encoded in the query string.",
    ),

  // --- Dates ---
  movein: z
    .string()
    .optional()
    .describe(
      "Move-in date. Format: 'Mon D, YYYY' (e.g. 'Aug 1, 2026', 'Jan 15, 2026'). " +
        "Used for mid-term rental date filtering.",
    ),
  moveout: z
    .string()
    .optional()
    .describe(
      "Move-out date. Format: 'Mon D, YYYY' (e.g. 'Aug 31, 2026', 'Jun 30, 2026'). " +
        "If omitted or flexible, listings may show 'flex' end dates.",
    ),

  // --- Price ---
  min_price: z
    .number()
    .optional()
    .describe("Minimum monthly rent in USD. Placeholder shows $1,000."),
  max_price: z
    .number()
    .optional()
    .describe("Maximum monthly rent in USD. Placeholder shows $1,000."),

  // --- Bedrooms ---
  bedrooms: z
    .enum(["1", "2", "3", "4", "5", "6"])
    .optional()
    .describe(
      "Number of available bedrooms. Values: '1', '2', '3', '4', '5', '6'. " +
        "Omit for 'Any' (no bedroom filter). " +
        "Note: listings show 'Studio' for studio apartments.",
    ),

  // --- Property types ---
  property_types: z
    .string()
    .optional()
    .describe(
      "Comma-separated property types. Known values: 'Apartment', 'House'. " +
        "Example: 'Apartment,House'. " +
        "Omit for all types.",
    ),

  // --- Type of place (accommodation type) ---
  type_of_places: z
    .string()
    .optional()
    .describe(
      "Comma-separated accommodation types. " +
        "Known values: 'Entire home', 'Private room'. " +
        "Example: 'Entire home' for whole-unit only. " +
        "Values with spaces get URL-encoded. Bubble double-encodes (%2520). " +
        "Omit for 'Any type'.",
    ),

  // --- Amenities ---
  amenities: z
    .string()
    .optional()
    .describe(
      "Comma-separated amenity filters (lowercase). " +
        "Known values: 'in-unit laundry', 'building laundry', 'gym', 'doorman'. " +
        "Example: 'gym,doorman'. " +
        "Omit for no amenity filter.",
    ),

  // --- Pet policy ---
  pet_policy: z
    .string()
    .optional()
    .describe(
      "Pet policy filter. " +
        "Known values: 'pets allowed', 'pets prohibited'. " +
        "Example: 'pets allowed' to filter for pet-friendly only. " +
        "Omit for no pet preference (All).",
    ),

  // --- Furnished status ---
  furnished_status: z
    .string()
    .optional()
    .describe(
      "Comma-separated furnished status filter. " +
        "Known values: 'Move-in ready', 'Furnished', 'Unfurnished'. " +
        "Example: 'Furnished,Move-in ready'. " +
        "Note: this param may appear with all values when other filters are applied. " +
        "Omit for no preference.",
    ),

  // --- Roommate gender ---
  roommate: z
    .enum(["Female", "Male", "Non-binary"])
    .optional()
    .describe(
      "Preferred roommate gender filter. " +
        "Values: 'Female', 'Male', 'Non-binary'. " +
        "Omit for no gender preference.",
    ),

  // --- Max roommates ---
  max_roommates: z
    .enum(["1", "2", "3", "4", "5"])
    .optional()
    .describe(
      "Maximum number of roommates. Values: '1', '2', '3', '4', '5'. " +
        "Omit for 'Any' (no roommate count limit).",
    ),
});

export type LiveOhanaParams = z.infer<typeof liveohanaParamsSchema>;

// ---------------------------------------------------------------------------
// Serializer
// ---------------------------------------------------------------------------

function serializeLiveOhanaUrl(
  _baseUrl: string,
  params: unknown,
): string {
  const p = params as LiveOhanaParams;
  const base = "https://liveohana.ai/search";
  const searchParams = new URLSearchParams();

  if (p.location) searchParams.set("location", p.location);
  if (p.movein) searchParams.set("movein", p.movein);
  if (p.moveout) searchParams.set("moveout", p.moveout);
  if (p.min_price != null) searchParams.set("min_price", String(p.min_price));
  if (p.max_price != null) searchParams.set("max_price", String(p.max_price));
  if (p.bedrooms) searchParams.set("bedrooms", p.bedrooms);
  if (p.property_types) searchParams.set("property_types", p.property_types);
  if (p.type_of_places) searchParams.set("type_of_places", p.type_of_places);
  if (p.amenities) searchParams.set("amenities", p.amenities);
  if (p.pet_policy) searchParams.set("pet_policy", p.pet_policy);
  if (p.furnished_status) searchParams.set("furnished_status", p.furnished_status);
  if (p.roommate) searchParams.set("roommate", p.roommate);
  if (p.max_roommates) searchParams.set("max_roommates", p.max_roommates);

  const qs = searchParams.toString();
  return qs ? `${base}?${qs}` : base;
}

// ---------------------------------------------------------------------------
// Provider config
// ---------------------------------------------------------------------------

export const liveohanaConfig: ProviderUrlConfig = {
  id: "liveohana.ai",
  name: "LiveOhana",
  baseUrls: {
    rent: "https://liveohana.ai/search",
    // Mid-term rentals only — no buy, no short-term (they ARE the mid-term niche)
  },
  params: liveohanaParamsSchema,
  serialize: serializeLiveOhanaUrl,
  knownLocations: {
    // Primary markets based on their listings and Google Ads targeting
    "New York": "New York, NY, USA",
    Brooklyn: "Brooklyn, NY, USA",
    Queens: "Queens, NY, USA",
    "Jersey City": "Jersey City, NJ, USA",
    "San Francisco": "San Francisco, CA, USA",
    "Los Angeles": "Los Angeles, CA, USA",
    Boston: "Boston, MA, USA",
    Chicago: "Chicago, IL, USA",
    "Washington DC": "Washington, DC, USA",
    Seattle: "Seattle, WA, USA",
    Miami: "Miami, FL, USA",
    Austin: "Austin, TX, USA",
    Denver: "Denver, CO, USA",
  },
};
